
# html lang
language: en

# main menu navigation
menu:
   Home: /
   About: /about
   Contact: /contact
   Archives: /archives

search:
  path: search.xml
  field: post
  content: true
  template: search.xml

# stylesheets loaded in the <head>
stylesheets:
 - /css/hexo-theme-honeyworks.css
 - /css/github.min.css
 - /css/semantic.css

# scripts loaded in the end of the body
scripts:
 - /js/hexo-theme-honeyworks.js
 - /js/highlight.min.js
 - /js/search.js
 - /js/semantic.js

social:
  github: https://github.com
  twitter: https://baidu.com
  instagram: https://instagram.com
  weibo: https://weibo.com
  mail: lozhu20@solar.earth

tools:
  back:
    enable: true  # true | false  是否显示文章详情页面返回上一页按钮
  darkmode:
    enable: true # true | false  是否显示暗黑模式切换按钮，开发中
  search:
    enable: true # true | false  是否显示搜索按钮